# Generated by Django 4.0.1 on 2022-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterField(
            model_name='soat',
            name='file',
            field=models.FileField(null=True, upload_to='people'),
        ),
    ]
