# Generated by Django 4.0.1 on 2022-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='user_photo_path',
            field=models.ImageField(null=True, upload_to='people'),
        ),
    ]
