# Generated by Django 4.0.1 on 2022-02-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('people', '0002_alter_people_user_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AddField(
            model_name='people',
            name='profile_information',
            field=models.TextField(null=True),
        ),
    ]
