# Generated by Django 4.0.1 on 2022-02-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_people_business_id_people_profile_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
