# Generated by Django 4.0.1 on 2022-02-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_people_address_alter_people_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name_plural': 'Usuarios'},
        ),
    ]
