# Generated by Django 4.0.1 on 2022-06-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0002_accreditation_type_accreditation_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation_type',
            name='name',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
