# Generated by Django 4.0.1 on 2022-06-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0004_accreditation_type_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation_type',
            name='icon',
            field=models.TextField(blank=True, choices=[('verified_user', 'verified_user'), ('health_and_safety', 'verified_user'), ('security', 'verified_user'), ('shield', 'verified_user'), ('policy', 'verified_user'), ('privacy_tip', 'verified_user'), ('gpp_maybe', 'verified_user'), ('gpp_bad', 'verified_user'), ('safety_check', 'verified_user'), ('add_moderator', 'verified_user'), ('remove_moderator', 'verified_user')], max_length=60, null=True),
        ),
    ]
