# Generated by Django 4.0.1 on 2022-06-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0005_accreditation_type_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
