# Generated by Django 4.0.1 on 2022-03-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0005_rename_users_vehicles_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorization_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('enabled', models.CharField(choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Observado')], default=1, max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='binding_contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('registration_date', models.DateField()),
                ('due_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='binding_contratcs')),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=6)),
                ('concession', models.CharField(choices=[(1, 'C1'), (2, 'C2'), (3, 'C3'), (4, 'C4'), (5, 'C5'), (6, 'C6'), (7, 'C7'), (8, 'C8'), (9, 'C9'), (10, 'C10'), (11, 'C11')], default=1, max_length=10)),
                ('status', models.BooleanField()),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'route',
                'db_table': 'route',
                'ordering': ['route'],
            },
        ),
        migrations.CreateModel(
            name='procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceedings', models.CharField(max_length=6)),
                ('check_date', models.DateField(auto_now_add=True)),
                ('qualification', models.CharField(choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Observado')], default=1, max_length=30)),
                ('ancient_period', models.CharField(choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Observado')], default=1, max_length=30)),
                ('property_card', models.BooleanField()),
                ('RRPP_Newsletter', models.CharField(max_length=2)),
                ('bonding', models.BooleanField()),
                ('due_date', models.DateField()),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(auto_now=True, null=True)),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validations.authorization_documents')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validations.binding_contracts')),
                ('id_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validations.routes')),
                ('license_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name_plural': 'Tramites',
                'db_table': 'procedure',
                'ordering': ['proceedings'],
            },
        ),
    ]
