# Generated by Django 4.0.1 on 2022-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='check_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='routes',
            name='concession',
            field=models.CharField(choices=[(1, 'C1'), (2, 'C2'), (3, 'C3'), (4, 'C4'), (5, 'C5'), (6, 'C6'), (7, 'C7'), (8, 'C8'), (9, 'C9'), (10, 'C10'), (11, 'C11')], default='1', max_length=10),
        ),
    ]
