# Generated by Django 4.0.1 on 2022-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding_contracts',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='citv_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('OBSERVADO', 'Observado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='soat_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('OBSERVADO', 'Observado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='src_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('OBSERVADO', 'Observado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='svct_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('OBSERVADO', 'Observado')], max_length=13),
        ),
    ]
