# Generated by Django 4.0.1 on 2022-03-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_users_vehicles_owners'),
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='enabled',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=9),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='license_plate',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='score',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=9),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='seniority_period',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=9),
        ),
    ]
