# Generated by Django 4.0.1 on 2022-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0002_alter_procedure_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='citv_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='enabled',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=9),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='score',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=9),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='seniority_period',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=9),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='soat_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='src_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='svct_status',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13),
        ),
    ]
