# Generated by Django 4.0.1 on 2022-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0003_alter_procedure_citv_status_alter_procedure_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='validation_tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_antiquity', models.IntegerField()),
                ('status_years', models.BooleanField()),
            ],
        ),
    ]
