# Generated by Django 4.0.1 on 2022-03-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_validation_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization_documents',
            name='commnet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validations.validation_tools'),
        ),
        migrations.AlterField(
            model_name='authorization_documents',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
