# Generated by Django 4.0.1 on 2022-03-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_users_vehicles_owners'),
        ('validations', '0006_procedure_year_proceeding_alter_routes_concession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='year_proceeding',
            field=models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, max_length=4),
        ),
        migrations.CreateModel(
            name='vehicle_substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustitucion', models.BooleanField()),
                ('exit_ticket', models.BooleanField()),
                ('vehicle_authorization_document', models.BooleanField()),
                ('file_authorization', models.FileField(blank=True, null=True, upload_to='substitution')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='substitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validations.vehicle_substitution'),
        ),
    ]
