# Generated by Django 4.0.1 on 2022-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0008_alter_procedure_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route',
            field=models.CharField(max_length=16),
        ),
    ]
