# Generated by Django 4.0.1 on 2022-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0009_alter_routes_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='route',
            field=models.CharField(max_length=45),
        ),
    ]
