# Generated by Django 4.0.1 on 2022-05-27 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0007_alter_soat_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0005_rename_users_vehicles_owners'),
        ('validations', '0010_alter_routes_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalprocedure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('proceedings', models.CharField(max_length=6)),
                ('year_proceeding', models.CharField(max_length=4)),
                ('check_date', models.DateField()),
                ('score', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=9)),
                ('property_card', models.BooleanField()),
                ('seniority_period', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=9)),
                ('soat_status', models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13)),
                ('citv_status', models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13)),
                ('src_status', models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13)),
                ('svct_status', models.CharField(choices=[('VIGENTE', 'vigente'), ('NO VIGENTE', 'No vigente'), ('INDETERMINADO', 'Indeterminado')], max_length=13)),
                ('RRPP_Newsletter', models.BooleanField()),
                ('bonding_contract', models.BooleanField()),
                ('enabled', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=9)),
                ('vehicle_authorization', models.BooleanField()),
                ('check_sistran', models.BooleanField()),
                ('due_date', models.DateField()),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(blank=True, editable=False)),
                ('update_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authorization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='validations.authorization_documents')),
                ('citv', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certify.citv')),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='validations.binding_contracts')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license_plate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vehicles.vehicles')),
                ('route', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='validations.routes')),
                ('soat', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certify.soat')),
                ('src', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certify.src')),
                ('substitution', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='validations.vehicle_substitution')),
                ('svct', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certify.svct')),
                ('years', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='validations.validation_tools')),
            ],
            options={
                'verbose_name': 'historical procedure',
                'verbose_name_plural': 'historical Tramites',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
