# Generated by Django 4.0.1 on 2022-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0011_historicalprocedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='concession',
            field=models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Historicalprocedure',
        ),
    ]
