# Generated by Django 4.0.1 on 2022-06-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='economic_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('category', models.IntegerField()),
                ('sub_category', models.IntegerField()),
                ('heading', models.CharField(max_length=150)),
                ('status', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades economicas',
                'db_table': 'economic_activities',
                'ordering': ['heading'],
            },
        ),
        migrations.CreateModel(
            name='geographic_location',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('captial', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'ubicacion geografica',
                'db_table': 'geographic_location',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='marial_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Estado Civil',
                'db_table': 'marial_status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'sexo',
                'db_table': 'sex',
                'ordering': ['id'],
            },
        ),
    ]
