# Generated by Django 4.0.1 on 2022-02-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_marial_status_options_alter_sex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic_activities',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
