# Generated by Django 4.0.1 on 2022-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_key_consulting_key_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
