# Generated by Django 4.0.1 on 2022-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='economic_activitie',
            field=models.ManyToManyField(blank=True, to='control.economic_activities'),
        ),
    ]
