# Generated by Django 4.0.1 on 2022-06-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_small_path',
            field=models.ImageField(blank=True, null=True, upload_to='bussines/%Y/%m/%d'),
        ),
    ]
