# Generated by Django 4.0.1 on 2022-02-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_large_path',
            field=models.ImageField(null=True, upload_to='bussines'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo_small_path',
            field=models.ImageField(null=True, upload_to='bussines'),
        ),
    ]
