# Generated by Django 4.0.1 on 2022-05-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_economic_activitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_large_path',
            field=models.ImageField(blank=True, null=True, upload_to='bussines'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo_small_path',
            field=models.ImageField(blank=True, null=True, upload_to='bussines'),
        ),
    ]
