# Generated by Django 4.0.1 on 2022-02-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_logo_large_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.TextField(null=True),
        ),
    ]
