# Generated by Django 4.0.1 on 2022-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_logo_large_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='small_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
