# Generated by Django 4.0.1 on 2022-02-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='opening_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
