# Generated by Django 4.0.1 on 2022-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tipo'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['plate'], 'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
