# Generated by Django 4.0.1 on 2022-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='users',
            field=models.ManyToManyField(blank=True, to='people.people'),
        ),
    ]
