# Generated by Django 4.0.1 on 2022-02-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicles_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
