# Generated by Django 4.0.1 on 2022-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_types_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
