# Generated by Django 4.0.1 on 2022-03-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_types_delete_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='users',
            new_name='owners',
        ),
    ]
