# Generated by Django 4.0.1 on 2022-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src',
            name='file',
            field=models.FileField(null=True, upload_to='people'),
        ),
    ]
