# Generated by Django 4.0.1 on 2022-02-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='scopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Alcances',
                'db_table': 'scopes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='types_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo de servicio',
                'db_table': 'Type of service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='svct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registration_date', models.DateTimeField()),
                ('date_expiry', models.DateTimeField()),
                ('file', models.FileField(null=True, upload_to='people')),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('vehicles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name_plural': 'SVCT',
                'db_table': 'SVCT',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='src',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registration_date', models.DateTimeField()),
                ('date_expiry', models.DateTimeField()),
                ('file', models.FileField(null=True, upload_to='people')),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('vehicles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name_plural': 'SRC',
                'db_table': 'SRC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='soat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=8)),
                ('certify', models.CharField(max_length=10)),
                ('insurance_company', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('registration_date', models.DateTimeField()),
                ('date_expiry', models.DateTimeField()),
                ('vin_serie', models.CharField(max_length=15)),
                ('insured', models.CharField(max_length=150)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('file', models.FileField(null=True, upload_to='people')),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certify.categories')),
                ('owners', models.ManyToManyField(to='owner.owner')),
                ('vehicles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name_plural': 'SOAT',
                'db_table': 'SOAT',
                'ordering': ['-insurance_company'],
            },
        ),
        migrations.CreateModel(
            name='citv',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('Registration_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('inspection_result', models.BooleanField()),
                ('comment', models.TextField()),
                ('Type_of_inspection', models.CharField(max_length=150)),
                ('file', models.FileField(null=True, upload_to='citv')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certify.scopes')),
                ('type_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certify.types_services')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name_plural': 'CITV',
                'db_table': 'citv',
                'ordering': ['Type_of_inspection'],
            },
        ),
    ]
