# Generated by Django 4.0.1 on 2022-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('certify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soat',
            name='owners',
            field=models.ManyToManyField(blank=True, to='people.people'),
        ),
    ]
