# Generated by Django 4.0.1 on 2022-03-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_economic_activitie'),
        ('certify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soat',
            name='file',
            field=models.FileField(null=True, upload_to='soat'),
        ),
        migrations.AlterField(
            model_name='soat',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
    ]
