# Generated by Django 4.0.1 on 2022-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0002_alter_citv_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='src',
            name='date_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='src',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='svct',
            name='date_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='svct',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
