# Generated by Django 4.0.1 on 2022-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0002_alter_soat_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citv',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='src',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='src',
            name='file',
            field=models.FileField(null=True, upload_to='src'),
        ),
        migrations.AlterField(
            model_name='svct',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='svct',
            name='file',
            field=models.FileField(null=True, upload_to='svct'),
        ),
    ]
