# Generated by Django 4.0.1 on 2022-03-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0003_alter_citv_delete_at_alter_src_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soat',
            name='date_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='soat',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
