# Generated by Django 4.0.1 on 2022-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0003_alter_src_date_expiry_alter_src_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='citv'),
        ),
        migrations.AlterField(
            model_name='soat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='soat'),
        ),
        migrations.AlterField(
            model_name='soat',
            name='vin_serie',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='src',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='src'),
        ),
        migrations.AlterField(
            model_name='svct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='svct'),
        ),
    ]
