# Generated by Django 4.0.1 on 2022-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0004_alter_citv_file_alter_soat_file_alter_soat_vin_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soat',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
