# Generated by Django 4.0.1 on 2022-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0004_alter_soat_date_expiry_alter_soat_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soat',
            name='certify',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='soat',
            name='policy',
            field=models.CharField(max_length=15),
        ),
    ]
