# Generated by Django 4.0.1 on 2022-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0005_alter_soat_certify_alter_soat_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citv',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
