# Generated by Django 4.0.1 on 2022-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0006_alter_citv_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soat',
            options={'ordering': ['insurance_company'], 'verbose_name_plural': 'SOAT'},
        ),
    ]
