# Generated by Django 4.0.1 on 2022-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=250)),
                ('route', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
