# Generated by Django 4.0.1 on 2022-06-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
