# Generated by Django 4.0.1 on 2022-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('user', '0003_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ManyToManyField(to='administration.profiles'),
        ),
    ]
