# Generated by Django 4.0.1 on 2022-02-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'scopes',
                'db_table': 'scopes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='types_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'type_of_service',
                'db_table': 'Type of service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='citv',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('Registration_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('inspection_result', models.BooleanField()),
                ('comment', models.TextField()),
                ('Type_of_inspection', models.CharField(max_length=150)),
                ('file', models.FilePathField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citv.scopes')),
                ('type_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citv.types_services')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name_plural': 'CITV',
                'db_table': 'citv',
                'ordering': ['Type_of_inspection'],
            },
        ),
    ]
