# Generated by Django 4.0.1 on 2022-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'ordering': ['name'], 'verbose_name_plural': 'Alcances'},
        ),
        migrations.AlterModelOptions(
            name='types_services',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tipo de servicio'},
        ),
        migrations.AlterField(
            model_name='citv',
            name='file',
            field=models.FileField(null=True, upload_to='citv'),
        ),
    ]
